// Code generated by swaggo/swag. DO NOT EDIT

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {"schemas":{"controller.Data":{"properties":{"title":{"example":"Object data","type":"string"}},"type":"object"},"controller.Response":{"properties":{"map_data":{"additionalProperties":{"type":"string"},"example":{"key":"value","key2":"value2"},"type":"object"},"object":{"$ref":"#/components/schemas/controller.Data"},"title":{"additionalProperties":{"type":"string"},"example":{"en":"Map","kk":"Карталар","ru":"Карта"},"type":"object"}},"type":"object"}}},
    "info": {"description":"{{escape .Description}}","license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0.html"},"termsOfService":"http://swagger.io/terms/","title":"{{.Title}}","version":"{{.Version}}"},
    "externalDocs": {"description":"","url":""},
    "paths": {"/test":{"get":{"description":"test\ntest\ntest\ntest\ntest\ntest","operationId":"get-map","responses":{"200":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/controller.Response"}}},"description":"OK"}},"summary":"Get Map Example"}}},
    "openapi": "3.1.0"
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Swagger Map Example API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
